# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: greetings.proto for package ''

require 'grpc'
require 'greetings_pb'

module Greetings
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Greetings'

    rpc :Hello, HelloRequest, HelloResponse
  end

  Stub = Service.rpc_stub_class
end
